name: Nix flake check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  nix-flake-check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Allow unprivileged user namespaces
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Run flake checks
        run: nix flake check
